### ISSUE TITLE
デフォルトオプション設定の拡張

### ISSUE THREAD

**Issue by upinetree** [upinetree/nicorepo#7]
`.nicorepo.yaml`に書く

```
days:
  general: 3
last:
  videos: true
```
